/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Career, CareerCategory, CareerAssessmentQuestion } from '../../types/career';

export const INITIAL_CAREER_CATEGORIES: CareerCategory[] = [
  'Technology',
  'Engineering',
  'Healthcare',
  'Business',
  'Finance',
  'Law',
  'Education',
  'Agriculture',
  'Media',
  'Design',
  'Hospitality',
  'Tourism',
  'Science',
  'Government',
  'Social Sciences',
  'Trades',
  'Entrepreneurship',
  'Creative Industries',
  'Environmental Careers',
  'Other',
];

export const INITIAL_CAREERS: Career[] = [
  {
    id: 'software-engineer',
    title: 'Full-Stack Software Engineer',
    tagline: 'Architect and build scalable web, mobile, and cloud software solutions.',
    description:
      'Full-Stack Software Engineers design, develop, test, and deploy end-to-end software applications. They manage both frontend user interfaces and backend server architectures, APIs, and databases.',
    category: 'Technology',
    industries: ['Software & SaaS', 'Financial Technology (FinTech)', 'E-Commerce', 'Telecommunications', 'Healthcare Tech'],
    requiredSkills: ['JavaScript / TypeScript', 'React / Modern Frontend', 'Node.js or Python Backend', 'SQL & Database Design', 'Git Version Control', 'REST APIs'],
    recommendedSkills: ['Docker & Containerization', 'Cloud Architecture (AWS / GCP / Azure)', 'GraphQL', 'CI/CD Pipelines', 'System Architecture', 'Test-Driven Development (TDD)'],
    futureSkills: ['AI-Augmented Software Engineering', 'Serverless Edge Compute', 'WebAssembly', 'Micro-Frontend Architecture'],
    relatedProgrammes: [
      'BSc. Computer Science',
      'BSc. Software Engineering',
      'BSc. Information Technology',
      'BSc. Business Information Technology',
      'BSc. Electrical & Information Engineering',
    ],
    relatedSubjects: ['Data Structures & Algorithms', 'Database Systems', 'Object Oriented Programming', 'Operating Systems', 'Web Application Development'],
    educationRequirements: {
      minimumLevel: 'Bachelors',
      recommendedMajor: 'Computer Science, Software Engineering, or IT',
      alternativePathways: ['Technical Bootcamp + Portfolio', 'Self-Taught with Verified Open Source Contributions'],
    },
    certifications: [
      {
        id: 'aws-cda',
        name: 'AWS Certified Developer - Associate',
        issuer: 'Amazon Web Services',
        level: 'Intermediate',
        description: 'Validates core AWS services, container orchestration, and cloud-native serverless development.',
      },
      {
        id: 'meta-frontend',
        name: 'Meta Front-End Developer Professional Certificate',
        issuer: 'Meta / Coursera',
        level: 'Entry',
        description: 'Comprehensive frontend development with React, JavaScript, UX principles, and version control.',
      },
    ],
    entryLevelRoles: ['Junior Software Engineer', 'Frontend Developer', 'Backend API Developer', 'Associate Full-Stack Developer'],
    progressionRoles: ['Senior Software Engineer', 'Tech Lead', 'Software Architect', 'Engineering Manager', 'VP of Engineering'],
    salaryInformation: [
      {
        country: 'Kenya',
        currency: 'KES',
        entryLevel: 'KSh 80,000 - 150,000 / mo',
        midLevel: 'KSh 180,000 - 350,000 / mo',
        seniorLevel: 'KSh 400,000 - 800,000+ / mo',
        sourceNote: 'Aggregated regional tech compensation benchmark 2025/2026',
      },
      {
        country: 'United Kingdom',
        currency: 'GBP',
        entryLevel: '£30,000 - £45,000 / yr',
        midLevel: '£50,000 - £75,000 / yr',
        seniorLevel: '£85,000 - £130,000+ / yr',
        sourceNote: 'UK Tech Talent Index',
      },
      {
        country: 'United States',
        currency: 'USD',
        entryLevel: '$75,000 - $110,000 / yr',
        midLevel: '$120,000 - $170,000 / yr',
        seniorLevel: '$180,000 - $280,000+ / yr',
        sourceNote: 'US Bureau of Labor Statistics & Tech Payscales',
      },
    ],
    countries: ['Kenya', 'United Kingdom', 'United States', 'Nigeria', 'South Africa', 'Germany', 'Remote Worldwide'],
    remotePossible: true,
    remotePotentialScore: 95,
    entrepreneurshipPotentialScore: 90,
    freelanceViabilityScore: 92,
    pathways: ['Corporate Employment', 'Freelancing & Consulting', 'Startup & Entrepreneurship'],
    entrepreneurshipIdeas: [
      'Build specialized vertical SaaS for African logistics, healthcare, or school management',
      'Launch an automated e-commerce integration consultancy',
      'Develop mobile-first micro-fintech tools integrating M-PESA APIs',
    ],
    freelanceNiches: ['Custom Next.js & React Web Apps', 'REST/GraphQL API Development', 'Third-Party API Integration & Automation'],
    learningResources: [
      {
        id: 'fullstack-open',
        title: 'Full Stack Open (University of Helsinki)',
        provider: 'University of Helsinki',
        type: 'course',
        url: 'https://fullstackopen.com/en/',
        isFree: true,
        durationEstimate: '60 hours',
        skillTaught: 'React, Node.js, Express, TypeScript, GraphQL, CI/CD',
        enemindVerified: true,
      },
      {
        id: 'cs50w',
        title: 'CS50W: Web Programming with Python and JavaScript',
        provider: 'Harvard University / edX',
        type: 'course',
        url: 'https://cs50.harvard.edu/web/',
        isFree: true,
        durationEstimate: '45 hours',
        skillTaught: 'Python, Django, JavaScript, SQL, Scalability',
        enemindVerified: true,
      },
    ],
    projectTemplates: [
      {
        id: 'proj-swe-1',
        title: 'Interactive Student Grade & GPA Simulator',
        difficulty: 'Beginner',
        description: 'Build a responsive web calculator that computes semester GPA and cumulative marks with local storage persistence.',
        skillsPracticed: ['TypeScript', 'React', 'Tailwind CSS', 'State Management'],
        suggestedTools: ['Vite', 'React', 'Tailwind CSS'],
        deliverables: ['Working web app on GitHub Pages/Vercel', 'Clean README with setup instructions'],
        estimatedHours: 12,
      },
      {
        id: 'proj-swe-2',
        title: 'Full-Stack M-PESA Payment & Inventory Management Hub',
        difficulty: 'Intermediate',
        description: 'Develop a multi-tenant business dashboard with Express API, PostgreSQL database, and simulated or sandbox mobile money STK push.',
        skillsPracticed: ['Node.js', 'Express', 'PostgreSQL', 'M-PESA Daraja API', 'Authentication'],
        suggestedTools: ['Express', 'PostgreSQL / Supabase', 'React', 'JWT'],
        deliverables: ['GitHub repository', 'Live deployed web app with live sandbox testing', 'Postman API documentation collection'],
        estimatedHours: 30,
      },
      {
        id: 'proj-swe-3',
        title: 'Distributed Real-Time Collaboration Workspace',
        difficulty: 'Advanced',
        description: 'Architect a collaborative document editor with WebSocket synchronization, optimistic UI updates, and role-based access control.',
        skillsPracticed: ['WebSockets', 'Redis', 'Docker', 'System Architecture', 'CI/CD Pipelines'],
        suggestedTools: ['Socket.io', 'Redis', 'Docker', 'React Flow'],
        deliverables: ['Multiplayer live demo', 'Architecture diagrams', 'Automated GitHub Actions CI/CD test pipeline'],
        estimatedHours: 50,
      },
    ],
    toolsAndTech: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Git', 'Docker', 'AWS', 'Tailwind CSS'],
    whatProfessionalsDo: [
      'Write clean, modular, and maintainable frontend and backend source code.',
      'Design relational schemas and optimize database querying speed.',
      'Collaborate with product designers and engineering managers in agile sprints.',
      'Conduct peer code reviews, write automated unit tests, and resolve security vulnerabilities.',
    ],
    isVerified: true,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'automation-engineer',
    title: 'Industrial & Automation Systems Engineer',
    tagline: 'Program PLCs, SCADA networks, industrial robotics, and IoT instrumentation.',
    description:
      'Automation Engineers bridge electrical hardware and software systems to automate industrial plants, energy grids, manufacturing lines, and agricultural processing facilities.',
    category: 'Engineering',
    industries: ['Manufacturing & FMCG', 'Energy & Power Distribution', 'Agriculture & Food Processing', 'Mining & Heavy Industries', 'Smart Buildings'],
    requiredSkills: ['PLC Programming (Ladder Logic, FBD)', 'SCADA & HMI Design', 'Electrical Circuits & Schematics', 'Industrial Sensors & Actuators', 'Instrumentation & Calibration', 'Safety Regulations & EBK Standards'],
    recommendedSkills: ['Industrial IoT (MQTT, OPC UA)', 'Embedded C/C++', 'Python for Industrial Analytics', 'Pneumatics & Hydraulics', 'Motor Drives & VFDs', 'Control Systems Theory (PID)'],
    futureSkills: ['AI-Driven Predictive Maintenance', 'Cobots (Collaborative Robotics)', 'Digital Twin Simulation', 'Cybersecurity for OT/SCADA'],
    relatedProgrammes: [
      'BSc. Electrical & Electronic Engineering',
      'BSc. Mechatronic Engineering',
      'BSc. Mechanical Engineering',
      'BSc. Control & Instrumentation Engineering',
      'BSc. Telecommunications & Information Engineering',
    ],
    relatedSubjects: ['Control Systems', 'Microprocessor Systems', 'Power Electronics', 'Industrial Automation', 'Sensors & Transducers'],
    educationRequirements: {
      minimumLevel: 'Bachelors',
      recommendedMajor: 'Electrical & Electronic, Mechatronic, or Mechanical Engineering',
      alternativePathways: ['Higher National Diploma in Electrical/Mechatronics Engineering + Apprenticeship'],
    },
    certifications: [
      {
        id: 'ebk-grad',
        name: 'Engineers Board of Kenya (EBK) Graduate Engineer Registration',
        issuer: 'Engineers Board of Kenya',
        level: 'Professional',
        description: 'Mandatory professional regulatory licensing for practicing engineers in Kenya.',
      },
      {
        id: 'isa-cap',
        name: 'ISA Certified Automation Professional (CAP)',
        issuer: 'International Society of Automation',
        level: 'Professional',
        description: 'Globally recognized certification for automation, PLC programming, and control systems design.',
      },
      {
        id: 'siemens-tia',
        name: 'Siemens TIA Portal & S7-1200/1500 PLC Specialist',
        issuer: 'Siemens Industrial Academy',
        level: 'Intermediate',
        description: 'Practical certification on Siemens industrial controller programming and HMI development.',
      },
    ],
    entryLevelRoles: ['Graduate Trainee Automation Engineer', 'Instrumentation Technician', 'Junior Control Systems Engineer', 'Electrical Maintenance Engineer'],
    progressionRoles: ['Senior Automation Engineer', 'Plant Engineering Manager', 'Chief Electrical Engineer', 'Industrial Automation Consultant'],
    salaryInformation: [
      {
        country: 'Kenya',
        currency: 'KES',
        entryLevel: 'KSh 70,000 - 130,000 / mo',
        midLevel: 'KSh 160,000 - 320,000 / mo',
        seniorLevel: 'KSh 380,000 - 700,000+ / mo',
        sourceNote: 'Federation of Kenya Employers & Manufacturing Industry surveys',
      },
      {
        country: 'Global',
        currency: 'USD',
        entryLevel: '$65,000 - $85,000 / yr',
        midLevel: '$90,000 - $130,000 / yr',
        seniorLevel: '$140,000 - $200,000+ / yr',
        sourceNote: 'IEEE & Automation World Benchmarks',
      },
    ],
    countries: ['Kenya', 'Germany', 'United States', 'South Africa', 'United Arab Emirates', 'Japan'],
    remotePossible: false,
    remotePotentialScore: 35,
    entrepreneurshipPotentialScore: 85,
    freelanceViabilityScore: 70,
    pathways: ['Corporate Employment', 'Freelancing & Consulting', 'Startup & Entrepreneurship', 'Public Sector & Government'],
    entrepreneurshipIdeas: [
      'Establish a precision agri-tech automation consultancy (automated greenhouse irrigation & sensor telemetry)',
      'Provide turnkey PLC retrofit and energy-efficiency audit services for local manufacturing plants',
      'Design custom solar-hybrid automation control boards for off-grid communities',
    ],
    freelanceNiches: ['PLC Ladder Logic Programming', 'SCADA Screen Design & Setup', 'Factory Commissioning & Troubleshooting'],
    learningResources: [
      {
        id: 'mit-control',
        title: 'Feedback Control Systems (MIT OpenCourseWare)',
        provider: 'MIT',
        type: 'course',
        url: 'https://ocw.mit.edu/courses/2-04a-systems-and-controls-spring-2019/',
        isFree: true,
        skillTaught: 'PID Control, Root Locus, Frequency Response, Transfer Functions',
        enemindVerified: true,
      },
      {
        id: 'realpars-plc',
        title: 'RealPars Industrial Automation Video Series',
        provider: 'RealPars Industrial Academy',
        type: 'video',
        url: 'https://realpars.com/',
        isFree: true,
        skillTaught: 'PLC programming, SCADA, Modbus, Fieldbus, VFDs',
        enemindVerified: true,
      },
    ],
    projectTemplates: [
      {
        id: 'proj-auto-1',
        title: 'Microcontroller Smart Hydroponic Climate Controller',
        difficulty: 'Beginner',
        description: 'Build an automated Arduino/ESP32 sensor station measuring soil moisture, water level, and temperature with relay actuators.',
        skillsPracticed: ['Circuit Prototyping', 'C/C++', 'Sensors & Actuators', 'Relay Switching'],
        suggestedTools: ['ESP32', 'Arduino IDE', 'DHT22 / Soil Capacitive Sensors', 'OLED Display'],
        deliverables: ['Schematic diagram in KiCad/Proteus', 'Working prototype demo video', 'Clean documented C++ firmware code'],
        estimatedHours: 16,
      },
      {
        id: 'proj-auto-2',
        title: 'Siemens/OpenPLC Industrial Bottle Sorting Simulator',
        difficulty: 'Intermediate',
        description: 'Simulate a 3-lane manufacturing sorting conveyor using OpenPLC, ladder logic programming, and a connected virtual HMI dashboard.',
        skillsPracticed: ['Ladder Logic', 'HMI Screen Design', 'Interlocking & State Machines', 'Safety Relays'],
        suggestedTools: ['OpenPLC Editor', 'ScadaBR', 'Factory I/O'],
        deliverables: ['Ladder logic program files', 'HMI supervisory screen captures', 'Functional specification report'],
        estimatedHours: 25,
      },
    ],
    toolsAndTech: ['Siemens TIA Portal', 'Rockwell Automation Studio 5000', 'AutoCAD Electrical', 'KiCad', 'Modbus / OPC-UA', 'MATLAB / Simulink'],
    whatProfessionalsDo: [
      'Draft electrical wiring diagrams, control panel layouts, and single-line diagrams.',
      'Program and test PLCs, PACs, and DCS controllers for automated equipment.',
      'Configure supervisory SCADA computer stations and touch-panel operator interfaces.',
      'Conduct site commissioning, factory acceptance tests (FAT), and emergency plant troubleshooting.',
    ],
    isVerified: true,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst & Business Intelligence Specialist',
    tagline: 'Transform raw institutional and market data into actionable strategic insights.',
    description:
      'Data Analysts query, clean, analyze, and visualize complex datasets to help executive teams make data-backed commercial and operational decisions.',
    category: 'Finance',
    industries: ['Banking & FinTech', 'Telecommunications', 'Management Consulting', 'Health Analytics', 'E-Commerce & Retail'],
    requiredSkills: ['SQL & Advanced Querying', 'Python or R for Data Analysis', 'Power BI / Tableau', 'Data Cleaning (Pandas)', 'Applied Statistics & Probability', 'Executive Dashboard Presentation'],
    recommendedSkills: ['Data Warehousing (BigQuery / Snowflake)', 'ETL Pipeline Design', 'Financial Modeling', 'A/B Testing & Experimentation', 'Excel VBA / Power Query', 'dbt (Data Build Tool)'],
    futureSkills: ['Generative AI for Analytics (Text-to-SQL)', 'Automated Feature Engineering', 'Causal Machine Learning', 'Data Observability'],
    relatedProgrammes: [
      'BSc. Applied Statistics & Computing',
      'BSc. Actuarial Science',
      'BSc. Economics & Statistics',
      'BSc. Computer Science',
      'BSc. Business Information Technology',
      'BSc. Financial Engineering',
    ],
    relatedSubjects: ['Probability & Mathematical Statistics', 'Econometrics', 'Database Management', 'Business Analytics', 'Linear Algebra'],
    educationRequirements: {
      minimumLevel: 'Bachelors',
      recommendedMajor: 'Statistics, Economics, Mathematics, Computer Science, or Finance',
      alternativePathways: ['Quantitative Diploma + Verified Capstone Portfolio'],
    },
    certifications: [
      {
        id: 'google-data-cert',
        name: 'Google Data Analytics Professional Certificate',
        issuer: 'Google / Coursera',
        level: 'Entry',
        description: 'Industry-standard foundational certificate covering spreadsheets, SQL, R, and Tableau visual storytelling.',
      },
      {
        id: 'microsoft-pl300',
        name: 'Microsoft Certified: Power BI Data Analyst Associate (PL-300)',
        issuer: 'Microsoft',
        level: 'Intermediate',
        description: 'Demonstrates data modeling, DAX calculations, and enterprise report publishing in Power BI.',
      },
    ],
    entryLevelRoles: ['Junior Data Analyst', 'Business Intelligence Associate', 'Operations Analyst', 'Reporting Specialist'],
    progressionRoles: ['Senior Data Analyst', 'BI Lead', 'Analytics Manager', 'Director of Business Intelligence', 'Chief Data Officer'],
    salaryInformation: [
      {
        country: 'Kenya',
        currency: 'KES',
        entryLevel: 'KSh 75,000 - 140,000 / mo',
        midLevel: 'KSh 160,000 - 320,000 / mo',
        seniorLevel: 'KSh 350,000 - 650,000+ / mo',
        sourceNote: 'East Africa Tech Talent Compendium 2025/2026',
      },
      {
        country: 'United States',
        currency: 'USD',
        entryLevel: '$65,000 - $90,000 / yr',
        midLevel: '$95,000 - $135,000 / yr',
        seniorLevel: '$140,000 - $190,000+ / yr',
        sourceNote: 'US Bureau of Labor Statistics',
      },
    ],
    countries: ['Kenya', 'United States', 'United Kingdom', 'Nigeria', 'Rwanda', 'South Africa', 'Remote Worldwide'],
    remotePossible: true,
    remotePotentialScore: 90,
    entrepreneurshipPotentialScore: 78,
    freelanceViabilityScore: 88,
    pathways: ['Corporate Employment', 'Freelancing & Consulting', 'Startup & Entrepreneurship'],
    entrepreneurshipIdeas: [
      'Launch a specialized retail & SME financial analytics dashboard service',
      'Provide churn-prediction and customer cohort analytics for emerging subscription apps',
      'Offer automated executive reporting automation via Google Sheets & Looker Studio',
    ],
    freelanceNiches: ['Executive Power BI Dashboards', 'SQL Query Optimization & ETL Pipelines', 'Financial Modeling & Forecasts'],
    learningResources: [
      {
        id: 'alex-the-analyst',
        title: 'Alex The Analyst Bootcamp Series',
        provider: 'Alex The Analyst / YouTube',
        type: 'video',
        url: 'https://www.youtube.com/c/AlexTheAnalyst',
        isFree: true,
        skillTaught: 'SQL, Excel, Tableau, Power BI, Python, Portfolio Projects',
        enemindVerified: true,
      },
      {
        id: 'kaggle-pandas',
        title: 'Kaggle Interactive Data Analysis Micro-Courses',
        provider: 'Kaggle',
        type: 'interactive',
        url: 'https://www.kaggle.com/learn/pandas',
        isFree: true,
        skillTaught: 'Pandas, Data Cleaning, Data Visualization, Feature Engineering',
        enemindVerified: true,
      },
    ],
    projectTemplates: [
      {
        id: 'proj-data-1',
        title: 'Telecommunications Customer Churn Exploratory Analysis',
        difficulty: 'Beginner',
        description: 'Analyze an open customer dataset with Python & Pandas to uncover primary factors driving subscription churn.',
        skillsPracticed: ['Python', 'Pandas', 'Matplotlib / Seaborn', 'Exploratory Data Analysis (EDA)'],
        suggestedTools: ['Jupyter Notebook / Google Colab', 'Pandas', 'Seaborn'],
        deliverables: ['Jupyter Notebook with documented insights', 'Summary slide deck with 5 actionable recommendations'],
        estimatedHours: 14,
      },
      {
        id: 'proj-data-2',
        title: 'Interactive Executive Sales & Revenue Power BI Dashboard',
        difficulty: 'Intermediate',
        description: 'Build a multi-page interactive Power BI dashboard featuring dynamic DAX KPIs, cohort drilldowns, and geographic revenue mapping.',
        skillsPracticed: ['Power BI', 'DAX Measures', 'Star Schema Data Modeling', 'Visual UX'],
        suggestedTools: ['Power BI Desktop', 'SQL / CSV Source Data'],
        deliverables: ['Published interactive Power BI report link', 'PDF documentation detailing data model & DAX calculations'],
        estimatedHours: 20,
      },
    ],
    toolsAndTech: ['SQL (PostgreSQL, BigQuery)', 'Python (Pandas, NumPy)', 'Power BI', 'Tableau', 'Excel / Sheets', 'Looker Studio', 'Git'],
    whatProfessionalsDo: [
      'Write complex SQL queries to extract data across production and transactional databases.',
      'Clean corrupt, duplicate, and missing data points before statistical analysis.',
      'Design intuitive charts, heatmaps, and executive dashboards for non-technical stakeholders.',
      'Present findings in weekly leadership meetings to guide marketing, pricing, and product strategies.',
    ],
    isVerified: true,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'cybersecurity-analyst',
    title: 'Cybersecurity & Information Security Analyst',
    tagline: 'Defend organizational networks, cloud systems, and data against cyber threats.',
    description:
      'Cybersecurity Analysts monitor computer networks for security breaches, perform vulnerability assessments, investigate cyber incidents, and implement firewalls and cryptographic protections.',
    category: 'Technology',
    industries: ['Banking & Financial Services', 'Defense & Government', 'Healthcare', 'Critical National Infrastructure', 'Cloud Providers'],
    requiredSkills: ['Network Protocols (TCP/IP, DNS, VPNs)', 'Linux Administration', 'Security Information & Event Management (SIEM)', 'Vulnerability Assessment', 'Incident Response', 'Identity & Access Management (IAM)'],
    recommendedSkills: ['Ethical Hacking & Penetration Testing', 'Python / Bash Scripting', 'Cloud Security (AWS/Azure)', 'Cryptography & PKI', 'MITRE ATT&CK Framework', 'Compliance & ISO 27001'],
    futureSkills: ['AI-Powered Threat Hunting', 'Zero-Trust Architecture', 'Quantum-Resistant Cryptography', 'DevSecOps Automation'],
    relatedProgrammes: [
      'BSc. Cybersecurity & Forensic Computing',
      'BSc. Computer Networks & Security',
      'BSc. Computer Science',
      'BSc. Information Technology',
      'BSc. Telecommunications Engineering',
    ],
    relatedSubjects: ['Network Security', 'Cryptography', 'Operating Systems', 'Computer Forensics', 'Ethical Hacking'],
    educationRequirements: {
      minimumLevel: 'Bachelors',
      recommendedMajor: 'Cybersecurity, Computer Science, or Network Engineering',
      alternativePathways: ['Recognized Security Certifications (CompTIA Security+, CEH) + CTF Competition Ranking'],
    },
    certifications: [
      {
        id: 'comptia-sec',
        name: 'CompTIA Security+ (SY0-701)',
        issuer: 'CompTIA',
        level: 'Entry',
        description: 'Industry benchmark certification establishing foundational knowledge in threats, attacks, and security controls.',
      },
      {
        id: 'isc2-cc',
        name: 'ISC2 Certified in Cybersecurity (CC)',
        issuer: 'ISC2',
        level: 'Entry',
        description: 'Global entry-level security credential covering access control, incident response, and networking concepts.',
      },
      {
        id: 'ceh',
        name: 'Certified Ethical Hacker (CEH)',
        issuer: 'EC-Council',
        level: 'Intermediate',
        description: 'Practical training on vulnerability scanning, exploitation vectors, and countermeasure implementation.',
      },
    ],
    entryLevelRoles: ['Junior SOC Analyst (Tier 1)', 'Information Security Associate', 'Junior Penetration Tester', 'Security Operations Technician'],
    progressionRoles: ['SOC Tier 2/3 Senior Analyst', 'Security Architect', 'Lead Incident Responder', 'Chief Information Security Officer (CISO)'],
    salaryInformation: [
      {
        country: 'Kenya',
        currency: 'KES',
        entryLevel: 'KSh 90,000 - 160,000 / mo',
        midLevel: 'KSh 200,000 - 400,000 / mo',
        seniorLevel: 'KSh 450,000 - 900,000+ / mo',
        sourceNote: 'Kenya Cyber Security Alliance & Banking sector compensation reviews',
      },
      {
        country: 'United Kingdom',
        currency: 'GBP',
        entryLevel: '£32,000 - £48,000 / yr',
        midLevel: '£55,000 - £80,000 / yr',
        seniorLevel: '£90,000 - £140,000+ / yr',
        sourceNote: 'UK National Cyber Security Centre reports',
      },
    ],
    countries: ['Kenya', 'United Kingdom', 'United States', 'Israel', 'South Africa', 'United Arab Emirates', 'Remote Worldwide'],
    remotePossible: true,
    remotePotentialScore: 82,
    entrepreneurshipPotentialScore: 80,
    freelanceViabilityScore: 84,
    pathways: ['Corporate Employment', 'Public Sector & Government', 'Freelancing & Consulting', 'Startup & Entrepreneurship'],
    entrepreneurshipIdeas: [
      'Provide affordable continuous vulnerability scanning and phishing simulation audits for African fintechs & SACCOs',
      'Establish a cybersecurity awareness and data-privacy compliance consultancy for medical facilities',
    ],
    freelanceNiches: ['Penetration Testing & Web App Security Audits', 'Compliance Preparation (ISO 27001, GDPR, Kenya Data Protection Act)', 'SOC Alert Triage'],
    learningResources: [
      {
        id: 'tryhackme',
        title: 'TryHackMe Complete Beginner & Pre-Security Paths',
        provider: 'TryHackMe',
        type: 'interactive',
        url: 'https://tryhackme.com/',
        isFree: true,
        skillTaught: 'Linux, Networking, Web Fundamentals, Vulnerability Assessment',
        enemindVerified: true,
      },
      {
        id: 'prof-messer-sec',
        title: 'Professor Messer CompTIA Security+ Training Course',
        provider: 'Professor Messer',
        type: 'video',
        url: 'https://www.professormesser.com/security-plus/sy0-701/sy0-701-video/',
        isFree: true,
        skillTaught: 'Threats, Vulnerabilities, Cryptography, Identity Management',
        enemindVerified: true,
      },
    ],
    projectTemplates: [
      {
        id: 'proj-sec-1',
        title: 'Home Lab Virtual SOC & SIEM Alert Pipeline',
        difficulty: 'Intermediate',
        description: 'Set up a virtualized lab environment using VirtualBox, deploy Elastic SIEM / Wazuh, and generate/analyze brute-force attack logs.',
        skillsPracticed: ['SIEM Configuration', 'Wazuh / Elastic', 'Log Analysis', 'Linux Virtualization'],
        suggestedTools: ['VirtualBox', 'Ubuntu Server', 'Wazuh', 'Splunk Free'],
        deliverables: ['Detailed home-lab topology architecture diagram', 'Incident triage walkthrough writeup on Medium/GitHub'],
        estimatedHours: 24,
      },
    ],
    toolsAndTech: ['Wireshark', 'Nmap', 'Burp Suite', 'Wazuh', 'Splunk', 'Linux (Kali/Ubuntu)', 'Snort', 'Metasploit'],
    whatProfessionalsDo: [
      'Monitor continuous SIEM alert feeds for suspicious network intrusions and malware executions.',
      'Investigate security incidents, isolate compromised endpoints, and conduct root-cause forensics.',
      'Perform regular automated vulnerability scans and verify patching compliance across servers.',
      'Educate company employees on phishing threats and secure credential handling.',
    ],
    isVerified: true,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'civil-structural-engineer',
    title: 'Civil & Structural Infrastructure Engineer',
    tagline: 'Design, plan, and supervise sustainable roads, bridges, water supply systems, and buildings.',
    description:
      'Civil and Structural Engineers design and manage physical infrastructure projects. They perform structural calculations, ensure compliance with geotechnical conditions, and oversee construction execution.',
    category: 'Engineering',
    industries: ['Construction & Contracting', 'Transportation & Highways', 'Water & Sanitation Infrastructure', 'Real Estate Development', 'Government & Municipalities'],
    requiredSkills: ['Structural Analysis (Eurocodes / BS Standards)', 'AutoCAD & Civil 3D', 'Geotechnical Soil Mechanics', 'Reinforced Concrete & Steel Design', 'Bill of Quantities (BoQ) & Cost Estimation', 'Site Supervision & Quality Control'],
    recommendedSkills: ['Building Information Modeling (BIM / Revit)', 'Prokon / SAP2000 / ETABS', 'Hydrology & Stormwater Modeling', 'Contract Management (FIDIC)', 'Environmental Impact Assessment (EIA)'],
    futureSkills: ['3D Concrete Printing', 'Green Sustainable Concrete (Low-Carbon)', 'Resilient Climate Infrastructure Modeling', 'Drone Photogrammetry & AI Site Audits'],
    relatedProgrammes: [
      'BSc. Civil Engineering',
      'BSc. Structural Engineering',
      'BSc. Construction Management',
      'BSc. Water & Environmental Engineering',
      'BSc. Geomatic Engineering',
    ],
    relatedSubjects: ['Theory of Structures', 'Fluid Mechanics & Hydraulics', 'Soil Mechanics & Foundations', 'Reinforced Concrete Design', 'Surveying & GIS'],
    educationRequirements: {
      minimumLevel: 'Bachelors',
      recommendedMajor: 'Civil Engineering or Structural Engineering',
      alternativePathways: ['Higher National Diploma in Civil Engineering + Board Examination'],
    },
    certifications: [
      {
        id: 'ebk-civil-grad',
        name: 'EBK Registered Graduate Engineer (Civil)',
        issuer: 'Engineers Board of Kenya',
        level: 'Professional',
        description: 'Mandatory statutory professional credential for civil engineering practice in Kenya.',
      },
      {
        id: 'autodesk-revit',
        name: 'Autodesk Certified Professional: Revit for Structural Design',
        issuer: 'Autodesk',
        level: 'Intermediate',
        description: 'Validates 3D structural modeling, detailing, and BIM integration capabilities.',
      },
    ],
    entryLevelRoles: ['Graduate Trainee Civil Engineer', 'Site Construction Engineer', 'Junior Structural Drafter', 'Assistant Materials Quality Engineer'],
    progressionRoles: ['Senior Structural Engineer', 'Project Resident Engineer', 'Chief Civil Engineer', 'Consulting Firm Principal Partner'],
    salaryInformation: [
      {
        country: 'Kenya',
        currency: 'KES',
        entryLevel: 'KSh 65,000 - 120,000 / mo',
        midLevel: 'KSh 150,000 - 300,000 / mo',
        seniorLevel: 'KSh 350,000 - 750,000+ / mo',
        sourceNote: 'Association of Consulting Engineers of Kenya (ACEK) surveys',
      },
      {
        country: 'United Kingdom',
        currency: 'GBP',
        entryLevel: '£28,000 - £40,000 / yr',
        midLevel: '£45,000 - £65,000 / yr',
        seniorLevel: '£70,000 - £110,000+ / yr',
        sourceNote: 'Institution of Civil Engineers (ICE) UK',
      },
    ],
    countries: ['Kenya', 'United Kingdom', 'Canada', 'Australia', 'South Africa', 'Tanzania', 'Uganda'],
    remotePossible: false,
    remotePotentialScore: 25,
    entrepreneurshipPotentialScore: 88,
    freelanceViabilityScore: 65,
    pathways: ['Corporate Employment', 'Public Sector & Government', 'Startup & Entrepreneurship', 'Freelancing & Consulting'],
    entrepreneurshipIdeas: [
      'Found a specialized civil engineering design consultancy for private residential & commercial developments',
      'Provide materials testing laboratory services (concrete compressive strength, soil California Bearing Ratio)',
      'Launch a sustainable eco-brick manufacturing or rainwater harvesting engineering enterprise',
    ],
    freelanceNiches: ['Structural Calculations & Local Council Submission Drawings', 'Bill of Quantities (BoQ) Estimation', '3D BIM Detailing in Revit'],
    learningResources: [
      {
        id: 'nptel-civil',
        title: 'NPTEL Design of Reinforced Concrete Structures',
        provider: 'IIT Kharagpur / NPTEL',
        type: 'course',
        url: 'https://nptel.ac.in/',
        isFree: true,
        skillTaught: 'Limit state design, beam shear, column buckling, slab deflection',
        enemindVerified: true,
      },
    ],
    projectTemplates: [
      {
        id: 'proj-civil-1',
        title: 'Structural Design & Detailing of a 4-Storey Commercial Building',
        difficulty: 'Intermediate',
        description: 'Perform manual limit-state design calculations for beams, slabs, columns, and isolated footings according to Eurocodes, followed by CAD detailing.',
        skillsPracticed: ['Eurocode Structural Design', 'AutoCAD Detailing', 'Bending Moment Diagrams', 'Reinforcement Schedules'],
        suggestedTools: ['AutoCAD', 'Prokon / Excel Calc Sheets', 'Eurocode 2 Manual'],
        deliverables: ['Calculation booklet with design checks', 'Full structural drawing set in PDF/DWG format'],
        estimatedHours: 35,
      },
    ],
    toolsAndTech: ['AutoCAD', 'Autodesk Revit', 'Prokon', 'ETABS / SAP2000', 'Civil 3D', 'Microsoft Project', 'GIS / QGIS'],
    whatProfessionalsDo: [
      'Calculate dead, live, wind, and seismic structural load combinations for proposed buildings.',
      'Prepare detailed reinforcement bending schedules and structural drawings for municipal building approval.',
      'Supervise on-site concrete pours, slump tests, and steel reinforcement alignment.',
      'Coordinate with architects, mechanical/electrical consultants, and quantity surveyors.',
    ],
    isVerified: true,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'agritech-specialist',
    title: 'AgriTech & Sustainable Agriculture Specialist',
    tagline: 'Modernize food systems with precision irrigation, drone mapping, and smart supply chains.',
    description:
      'AgriTech Specialists combine agronomic science with digital technologies, IoT sensors, climate forecasting, and modern post-harvest logistics to optimize crop yields and sustainable farming.',
    category: 'Agriculture',
    industries: ['Precision Farming & AgriTech', 'Commercial Horticulture & Exports', 'Food Processing & Agribusiness', 'Climate Adaptation & NGOs', 'Agri-FinTech'],
    requiredSkills: ['Agronomic Crop Management', 'Soil Fertility & Nutrient Testing', 'Drip Irrigation & Water Management', 'Post-Harvest Handling & Cold Chain', 'Agribusiness Financial Modeling', 'GlobalGAP / Export Quality Standards'],
    recommendedSkills: ['Drone Multispectral Imaging', 'GIS & Satellite Remote Sensing', 'Greenhouse Climate Automation', 'Hydroponics & Soilless Cultivation', 'Agricultural Carbon Credits'],
    futureSkills: ['AI-Driven Crop Disease Diagnostics', 'Robotic Harvesting & Weeding', 'Bio-Stimulants & Soil Microbiome Engineering'],
    relatedProgrammes: [
      'BSc. Agricultural & Biosystems Engineering',
      'BSc. Agribusiness Management',
      'BSc. Agriculture / Horticulture',
      'BSc. Food Science & Technology',
      'BSc. Environmental Science',
    ],
    relatedSubjects: ['Crop Production', 'Soil Science', 'Agricultural Engineering', 'Farm Management', 'Postharvest Technology'],
    educationRequirements: {
      minimumLevel: 'Bachelors',
      recommendedMajor: 'Agricultural Engineering, Agribusiness, or Agronomy',
      alternativePathways: ['Diploma in Agriculture/Horticulture + Field Farming Experience'],
    },
    certifications: [
      {
        id: 'globalgap-cert',
        name: 'GlobalGAP Farm Assessor & Food Safety Certification',
        issuer: 'GlobalGAP Academy',
        level: 'Intermediate',
        description: 'Industry standard certification for international agricultural export compliance and food safety.',
      },
    ],
    entryLevelRoles: ['Assistant Farm Manager', 'Agronomist Field Officer', 'AgriTech Technical Representative', 'Quality Control Inspector'],
    progressionRoles: ['Senior Agronomist', 'Commercial Farm Operations Director', 'Agribusiness Consultant', 'AgriTech Founder'],
    salaryInformation: [
      {
        country: 'Kenya',
        currency: 'KES',
        entryLevel: 'KSh 60,000 - 110,000 / mo',
        midLevel: 'KSh 140,000 - 280,000 / mo',
        seniorLevel: 'KSh 320,000 - 650,000+ / mo',
        sourceNote: 'Kenya Agricultural & Livestock Research Organization and Agribusiness benchmarks',
      },
      {
        country: 'Global',
        currency: 'USD',
        entryLevel: '$50,000 - $75,000 / yr',
        midLevel: '$80,000 - $115,000 / yr',
        seniorLevel: '$120,000 - $175,000+ / yr',
        sourceNote: 'FAO & Global AgriTech indices',
      },
    ],
    countries: ['Kenya', 'Netherlands', 'Israel', 'United States', 'Uganda', 'Rwanda', 'Ghana'],
    remotePossible: false,
    remotePotentialScore: 30,
    entrepreneurshipPotentialScore: 94,
    freelanceViabilityScore: 75,
    pathways: ['Startup & Entrepreneurship', 'Corporate Employment', 'NGO & International Development', 'Freelancing & Consulting'],
    entrepreneurshipIdeas: [
      'Launch a high-value export horticulture enterprise (avocados, herbs, chillies) using precision drip irrigation',
      'Provide mobile soil-testing and fertilizer recommendation services for smallholder farmers',
      'Build a digital B2B farm produce aggregation marketplace linking rural growers directly to urban retail',
    ],
    freelanceNiches: ['Farm Feasibility & Financial Projections', 'GlobalGAP Standard Audit Preparation', 'Drip Irrigation Network Design'],
    learningResources: [
      {
        id: 'fao-agri-hub',
        title: 'FAO Sustainable Agriculture & Water Management E-Learning',
        provider: 'United Nations FAO',
        type: 'course',
        url: 'https://elearning.fao.org/',
        isFree: true,
        skillTaught: 'Climate-Smart Agriculture, Drip Irrigation, Soil Conservation',
        enemindVerified: true,
      },
    ],
    projectTemplates: [
      {
        id: 'proj-agri-1',
        title: 'High-Yield Commercial Tomato Greenhouse Business & Agronomy Plan',
        difficulty: 'Intermediate',
        description: 'Design a complete 500sqm greenhouse setup including fertigation schedule, pest scouting protocol, and 3-year cash flow projections.',
        skillsPracticed: ['Fertigation Planning', 'Pest & Disease Management', 'Cash Flow Budgeting', 'Crop Scheduling'],
        suggestedTools: ['Excel Agribusiness Models', 'Climate & Pest Scouting Sheets'],
        deliverables: ['Comprehensive agronomic management guide', 'Financial sensitivity model'],
        estimatedHours: 20,
      },
    ],
    toolsAndTech: ['GPS / Drone Photogrammetry', 'Soil pH / EC Meters', 'AutoCAD / QGIS', 'FarmERP / Agworld', 'IoT Telemetry Sensors'],
    whatProfessionalsDo: [
      'Conduct soil chemical and physical analysis to formulate precision crop nutrition programs.',
      'Design pressurized drip and sprinkler irrigation layouts optimized for water conservation.',
      'Implement integrated pest management (IPM) protocols minimizing chemical pesticide residues.',
      'Analyze farm harvest data and cost-of-production metrics to maximize profitability per hectare.',
    ],
    isVerified: true,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'financial-analyst',
    title: 'Financial Analyst & Investment Specialist',
    tagline: 'Model corporate valuations, investment portfolios, and financial risk strategies.',
    description:
      'Financial Analysts evaluate investment opportunities, build quantitative discounted cash flow (DCF) models, assess creditworthiness, and advise corporate executives and funds on capital allocation.',
    category: 'Finance',
    industries: ['Investment Banking & Private Equity', 'Commercial Banking & Microfinance', 'Asset Management & Pension Funds', 'Corporate Finance & Treasury', 'FinTech'],
    requiredSkills: ['Financial Statement Analysis (P&L, Balance Sheet, Cash Flow)', 'Discounted Cash Flow (DCF) & Valuation', 'Advanced Financial Excel (Macros, Goal Seek)', 'Financial Markets & Macroeconomics', 'Corporate Finance Principles', 'Report Writing & Due Diligence'],
    recommendedSkills: ['Python for Quantitative Finance', 'SQL for Financial Datasets', 'Power BI Financial Dashboards', 'IFRS Standards & Tax Regulations', 'Venture Capital Term Sheet Analysis'],
    futureSkills: ['AI-Driven Algorithmic Trading', 'ESG & Carbon Accounting Analytics', 'DeFi & Digital Asset Risk Modeling'],
    relatedProgrammes: [
      'BSc. Finance & Banking',
      'BSc. Financial Engineering',
      'BSc. Economics & Finance',
      'BSc. Actuarial Science',
      'BSc. Commerce (Finance Option)',
      'BSc. Accounting',
    ],
    relatedSubjects: ['Corporate Finance', 'Investment Analysis & Portfolio Management', 'Financial Econometrics', 'Managerial Accounting', 'Commercial Law'],
    educationRequirements: {
      minimumLevel: 'Bachelors',
      recommendedMajor: 'Finance, Economics, Financial Engineering, or Accounting',
      alternativePathways: ['Bachelors in STEM + Certified Financial Analyst (CFA) Candidate Level 1'],
    },
    certifications: [
      {
        id: 'cfa-level1',
        name: 'Chartered Financial Analyst (CFA) Program',
        issuer: 'CFA Institute',
        level: 'Chartered',
        description: 'Gold standard international credential in investment analysis, portfolio management, and ethical finance.',
      },
      {
        id: 'cpa-k',
        name: 'Certified Public Accountants (CPA-K)',
        issuer: 'KASNEB (Kenya)',
        level: 'Professional',
        description: 'Premier statutory accounting and financial management qualification in Kenya.',
      },
      {
        id: 'cisi',
        name: 'Chartered Institute for Securities & Investment (CISI)',
        issuer: 'CISI UK / CMA Kenya',
        level: 'Intermediate',
        description: 'Recognized licensing qualification for capital markets and stockbrokerage practitioners.',
      },
    ],
    entryLevelRoles: ['Junior Financial Analyst', 'Equity Research Assistant', 'Credit Risk Analyst', 'Corporate Finance Associate'],
    progressionRoles: ['Senior Financial Analyst', 'Portfolio Manager', 'Investment Director', 'Chief Financial Officer (CFO)'],
    salaryInformation: [
      {
        country: 'Kenya',
        currency: 'KES',
        entryLevel: 'KSh 80,000 - 150,000 / mo',
        midLevel: 'KSh 180,000 - 380,000 / mo',
        seniorLevel: 'KSh 450,000 - 950,000+ / mo',
        sourceNote: 'Nairobi Securities Exchange (NSE) & Investment banking compensation reports',
      },
      {
        country: 'United Kingdom',
        currency: 'GBP',
        entryLevel: '£35,000 - £55,000 / yr',
        midLevel: '£60,000 - £95,000 / yr',
        seniorLevel: '£110,000 - £180,000+ / yr',
        sourceNote: 'London City Financial Surveys',
      },
    ],
    countries: ['Kenya', 'United Kingdom', 'United States', 'South Africa', 'United Arab Emirates', 'Remote Worldwide'],
    remotePossible: true,
    remotePotentialScore: 78,
    entrepreneurshipPotentialScore: 82,
    freelanceViabilityScore: 80,
    pathways: ['Corporate Employment', 'Freelancing & Consulting', 'Startup & Entrepreneurship'],
    entrepreneurshipIdeas: [
      'Found a boutique financial modeling and investor-readiness advisory firm for African startups',
      'Create a digital micro-investment / savings aggregation platform for university students and young professionals',
      'Provide outsourced CFO and bookkeeping services for growing SMEs',
    ],
    freelanceNiches: ['Investor Pitch Deck Financial Models', 'Business Valuation & DCF Models', 'SME Budgeting & Cash Flow Forecasting'],
    learningResources: [
      {
        id: 'damodaran-valuation',
        title: 'Aswath Damodaran Corporate Finance & Valuation Series',
        provider: 'NYU Stern / Prof. Aswath Damodaran',
        type: 'course',
        url: 'https://pages.stern.nyu.edu/~adamodar/',
        isFree: true,
        skillTaught: 'DCF Valuation, Cost of Capital, Multiples, Risk Assessment',
        enemindVerified: true,
      },
    ],
    projectTemplates: [
      {
        id: 'proj-fin-1',
        title: '3-Statement Financial Model & DCF Valuation of a Public Listed Company',
        difficulty: 'Intermediate',
        description: 'Build an interconnected 5-year financial forecast model (Income Statement, Balance Sheet, Cash Flow) with dynamic WACC calculation for a listed firm.',
        skillsPracticed: ['Financial Modeling', 'WACC Calculation', 'Scenario & Sensitivity Analysis', 'Discounted Cash Flow'],
        suggestedTools: ['Microsoft Excel', 'Financial Annual Reports (NSE / SEC filings)'],
        deliverables: ['Fully functional dynamic Excel model file', '10-page equity valuation research memorandum'],
        estimatedHours: 25,
      },
    ],
    toolsAndTech: ['Microsoft Excel (Advanced)', 'Bloomberg Terminal / Refinitiv', 'Power BI', 'Python (Quant / Pandas)', 'QuickBooks / Xero'],
    whatProfessionalsDo: [
      'Analyze historical financial statements, EBITDA margins, and working capital cycles.',
      'Construct multi-scenario financial forecasts incorporating inflation, interest rates, and currency risks.',
      'Prepare investment committee presentation memos for capital expenditure approvals.',
      'Perform company valuations and transaction multiples for merger and acquisition (M&A) deals.',
    ],
    isVerified: true,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
];

// ==========================================
// CAREER ASSESSMENT QUESTIONS
// Configurable Multi-Signal Assessment
// ==========================================

export const INITIAL_ASSESSMENT_QUESTIONS: CareerAssessmentQuestion[] = [
  {
    id: 1,
    category: 'interests',
    question: 'Which of the following activities naturally energizes you most?',
    subtitle: 'Choose the area where you find yourself deeply focused without forcing it.',
    options: [
      {
        id: 'opt-1-tech',
        label: 'Building software, automating workflows, or writing code',
        description: 'You love turning abstract logic into functional interactive applications or algorithms.',
        categoryWeights: { Technology: 35, Science: 15, Engineering: 15 },
        skillSignals: ['JavaScript / TypeScript', 'Python', 'Algorithms'],
        traitSignals: ['Logical', 'Technical', 'Problem Solver'],
      },
      {
        id: 'opt-1-eng',
        label: 'Working with physical machinery, circuits, structures, or hardware systems',
        description: 'You are fascinated by how physical machines, robots, buildings, or energy grids function.',
        categoryWeights: { Engineering: 35, Technology: 15, Trades: 15 },
        skillSignals: ['Circuit Design', 'AutoCAD', 'PLC Programming'],
        traitSignals: ['Hands-on', 'Systematic', 'Practical'],
      },
      {
        id: 'opt-1-fin',
        label: 'Analyzing financial trends, stock markets, numbers, and business metrics',
        description: 'You enjoy uncovering patterns in data, financial models, valuation, and economic forecasts.',
        categoryWeights: { Finance: 35, Business: 25, Technology: 10 },
        skillSignals: ['SQL', 'Financial Modeling', 'Data Analysis'],
        traitSignals: ['Analytical', 'Quantitative', 'Detail-oriented'],
      },
      {
        id: 'opt-1-agri',
        label: 'Cultivating crops, farming systems, nature, and environmental preservation',
        description: 'You are passionate about sustainable food production, agribusiness, and eco-conservation.',
        categoryWeights: { Agriculture: 35, 'Environmental Careers': 30, Science: 15 },
        skillSignals: ['Agronomy', 'Soil Testing', 'Irrigation'],
        traitSignals: ['Nature-aligned', 'Practical', 'Impact-driven'],
      },
    ],
  },
  {
    id: 2,
    category: 'strengths',
    question: 'How do your peers and professors typically describe your strongest mental trait?',
    subtitle: 'Think about the type of challenges where people naturally seek your guidance.',
    options: [
      {
        id: 'opt-2-analytical',
        label: 'Deep Analytical & Quantitative Rigor',
        description: 'You break complex ambiguous problems into mathematical and logical components with ease.',
        categoryWeights: { Technology: 25, Finance: 25, Engineering: 25, Science: 25 },
        traitSignals: ['Analytical', 'Methodical', 'Detail-oriented'],
      },
      {
        id: 'opt-2-creative',
        label: 'Visual Design, Creative Problem-Solving & Architecture',
        description: 'You synthesize intuitive, aesthetic, and out-of-the-box solutions that delight people.',
        categoryWeights: { Design: 30, Technology: 20, Media: 20, 'Creative Industries': 25 },
        traitSignals: ['Creative', 'Visual Thinker', 'User-Focused'],
      },
      {
        id: 'opt-2-leadership',
        label: 'Strategic Leadership, Negotiation & Commercial Acumen',
        description: 'You organize teams, identify market opportunities, and persuade stakeholders to take action.',
        categoryWeights: { Business: 30, Entrepreneurship: 30, Finance: 20, Government: 15 },
        traitSignals: ['Strategic', 'Persuasive', 'Organized'],
      },
      {
        id: 'opt-2-practical',
        label: 'Practical Execution, Diagnostics & Physical Troubleshooting',
        description: 'You excel at testing real hardware, building prototypes, and getting systems working under pressure.',
        categoryWeights: { Engineering: 30, Agriculture: 25, Trades: 25, Healthcare: 15 },
        traitSignals: ['Execution-Driven', 'Resilient', 'Hands-on'],
      },
    ],
  },
  {
    id: 3,
    category: 'workPreferences',
    question: 'What is your ideal work environment and day-to-day rhythm?',
    subtitle: 'Consider how you prefer your physical workspace, teamwork balance, and location flexibility.',
    options: [
      {
        id: 'opt-3-remote',
        label: 'Remote / Global Digital Nomad (Laptop & Internet Anywhere)',
        description: 'You thrive when given autonomy to deliver asynchronous results from any quiet space.',
        categoryWeights: { Technology: 30, Finance: 20, Design: 25, Media: 20 },
        traitSignals: ['Autonomous', 'Self-Motivated', 'Remote-Oriented'],
      },
      {
        id: 'opt-3-field',
        label: 'Dynamic Field Work, Plants, Construction Sites & Labs',
        description: 'You prefer inspecting real sites, overseeing physical installations, and active field mobility.',
        categoryWeights: { Engineering: 35, Agriculture: 35, 'Environmental Careers': 25 },
        traitSignals: ['Active', 'Field-Oriented', 'Observant'],
      },
      {
        id: 'opt-3-corporate',
        label: 'Fast-Paced Corporate Boardroom & Collaborative Office',
        description: 'You enjoy face-to-face team collaboration, pitching ideas to executives, and business networking.',
        categoryWeights: { Business: 30, Finance: 30, Law: 25, Government: 20 },
        traitSignals: ['Collaborative', 'Networker', 'Corporate-Savvy'],
      },
    ],
  },
  {
    id: 4,
    category: 'skills',
    question: 'Which of these technical or professional skillsets do you feel most drawn to developing deeply?',
    subtitle: 'Select the skill domain you are most excited to master over the next 12 to 24 months.',
    options: [
      {
        id: 'opt-4-code',
        label: 'Modern Programming, Cloud Architectures & Database Engineering',
        description: 'Mastering languages like TypeScript, Python, SQL, Docker, and scalable distributed systems.',
        categoryWeights: { Technology: 35, Science: 15, Engineering: 15 },
        skillSignals: ['JavaScript / TypeScript', 'SQL & Database Design', 'Git Version Control'],
        traitSignals: ['Technical', 'Continuous Learner'],
      },
      {
        id: 'opt-4-eng-tools',
        label: 'Industrial Automation, CAD Schematics, Embedded Systems & Instrumentation',
        description: 'Mastering PLC ladder logic, AutoCAD, microcontroller firmware, and hardware prototyping.',
        categoryWeights: { Engineering: 35, Trades: 20, Technology: 10 },
        skillSignals: ['PLC Programming', 'AutoCAD', 'Circuit Design'],
        traitSignals: ['Precision-Minded', 'System Builder'],
      },
      {
        id: 'opt-4-quant',
        label: 'Financial Modeling, Statistical Forecasting & Business Intelligence',
        description: 'Mastering DCF models, Power BI dashboards, statistical regressions, and market valuation.',
        categoryWeights: { Finance: 35, Business: 25, Technology: 15 },
        skillSignals: ['Financial Modeling', 'Power BI / Tableau', 'SQL'],
        traitSignals: ['Quantitative', 'Strategic'],
      },
      {
        id: 'opt-4-bio-agri',
        label: 'Sustainable Agri-Systems, Precision Fertigation & Environmental Auditing',
        description: 'Mastering soil nutrient testing, greenhouse automation, drip networks, and export standards.',
        categoryWeights: { Agriculture: 35, 'Environmental Careers': 30, Science: 20 },
        skillSignals: ['Agronomic Crop Management', 'Drip Irrigation', 'Soil Testing'],
        traitSignals: ['Eco-Conscious', 'Practical Agronomist'],
      },
    ],
  },
  {
    id: 5,
    category: 'goals',
    question: 'What is your primary overarching career aspiration over the next 5 to 10 years?',
    subtitle: 'What ultimate impact or lifestyle do you want your professional work to create?',
    options: [
      {
        id: 'opt-5-founder',
        label: 'Launch My Own Tech, Engineering, or Agribusiness Startup / Venture',
        description: 'You want to build an independent business, create jobs, and scale commercial solutions across Africa & globally.',
        categoryWeights: { Entrepreneurship: 35, Technology: 20, Agriculture: 20, Business: 20 },
        traitSignals: ['Entrepreneurial', 'Risk-Tolerant', 'Visionary'],
      },
      {
        id: 'opt-5-global',
        label: 'High-Earning Global Specialist / Remote International Career',
        description: 'You want to achieve world-class mastery, earning in strong currencies while working with top global teams.',
        categoryWeights: { Technology: 30, Finance: 30, Engineering: 20 },
        traitSignals: ['High-Ambition', 'Global-Mindset', 'Specialist'],
      },
      {
        id: 'opt-5-infra',
        label: 'Build Essential National Infrastructure & Industrial Capability',
        description: 'You want to construct vital energy grids, transport networks, manufacturing hubs, and public systems.',
        categoryWeights: { Engineering: 35, Government: 25, Agriculture: 20 },
        traitSignals: ['Nation-Builder', 'Reliable', 'Long-Term Impact'],
      },
    ],
  },
];
