import { Opportunity } from '../../types/opportunities';

// Base dynamic future dates relative to current runtime (2026/2027)
const getFutureDateStr = (daysFromNow: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().split('T')[0];
};

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-mc-2026',
    title: 'Mastercard Foundation Scholars Program',
    description:
      'A comprehensive scholarship and leadership development initiative designed to educate and develop transformative leaders across Africa. Covers full university tuition, modern accommodation, living stipend, laptop, health insurance, and structured mentorship.',
    provider: 'Mastercard Foundation',
    organization: 'Mastercard Foundation & Partner Universities',
    type: 'Scholarship',
    country: 'Pan-Africa',
    countries: ['Kenya', 'Uganda', 'Rwanda', 'Ghana', 'Nigeria', 'South Africa', 'Ethiopia', 'Tanzania'],
    location: 'Multiple Partner Campuses across Africa & Global',
    remote: false,
    website: 'https://mastercardfdn.org/all/scholars/',
    applicationUrl: 'https://mastercardfdn.org/all/scholars/becoming-a-scholar/apply-to-the-scholars-program/',
    field: 'All Fields',
    fields: ['Engineering', 'Computer Science', 'Health Sciences', 'Agriculture', 'Business Administration', 'Social Sciences'],
    eligibleUniversities: ['All accredited universities', 'University of Nairobi', 'JKUAT', 'Strathmore', 'KNUST', 'Ashesi', 'Makerere', 'UCT'],
    eligibleProgrammes: ['Undergraduate & Masters Degrees across STEM, Health, Agriculture, and Economics'],
    eligibleAcademicLevels: ['Undergraduate', 'Year 1', 'Year 2', 'Masters', 'Postgraduate'],
    requiredSkills: ['Leadership Potential', 'Community Engagement', 'Academic Excellence'],
    preferredSkills: ['Problem Solving', 'Volunteering Experience'],
    minimumGPA: 3.5,
    fundingAmount: '100% Tuition, Monthly Stipend, Housing, Airfare & Laptop',
    currency: 'USD',
    fundingType: 'Fully Funded',
    deadline: getFutureDateStr(45),
    startDate: '2026-09-01',
    endDate: '2030-07-31',
    duration: '4 Years (Degree Duration)',
    status: 'open',
    source: 'Mastercard Foundation Official Scholarships Portal',
    sourceUrl: 'https://mastercardfdn.org',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-01-15T09:00:00Z',
    featured: true,
    createdAt: '2026-01-10T12:00:00Z',
    updatedAt: '2026-02-01T12:00:00Z',
    scholarshipDetails: {
      coverageType: 'Full Funding',
      tuitionCoverage: true,
      accommodationCoverage: true,
      travelCoverage: true,
      livingAllowance: true,
      monthlyStipendAmount: '$450 USD equivalent',
      ageLimit: 29,
    },
  },
  {
    id: 'opp-saf-tech-2026',
    title: 'Safaricom Engineering & Tech Industrial Attachment',
    description:
      '3-month structured industrial attachment program for 3rd and 4th-year engineering and technology undergraduates. Interns rotate across telecommunications core network, cloud infrastructure, M-PESA APIs, and cyber security operations.',
    provider: 'Safaricom PLC',
    organization: 'Safaricom PLC (HQ Nairobi)',
    type: 'Attachment',
    country: 'Kenya',
    countries: ['Kenya'],
    location: 'Nairobi, Kenya (Safaricom HQ & Tech Hub)',
    remote: 'hybrid',
    website: 'https://www.safaricom.co.ke/careers',
    applicationUrl: 'https://www.safaricom.co.ke/careers/students-and-graduates',
    field: 'Engineering & Technology',
    fields: ['Electrical Engineering', 'Telecommunications Engineering', 'Computer Science', 'Software Engineering', 'Information Technology'],
    eligibleUniversities: ['All accredited universities in Kenya'],
    eligibleProgrammes: [
      'BSc. Electrical & Electronic Engineering',
      'BSc. Telecommunications & Information Engineering',
      'BSc. Computer Science',
      'BSc. Software Engineering',
      'BSc. Information Technology',
    ],
    eligibleAcademicLevels: ['Year 3', 'Year 4'],
    requiredSkills: ['Networking Basics', 'Python or C++', 'Linux Fundamentals', 'Problem Solving'],
    preferredSkills: ['Cloud Concepts (AWS/GCP)', 'REST APIs', 'Git'],
    minimumGPA: 3.0,
    fundingAmount: 'KSh 35,000 / month Stipend + NITA Approved Attachment Letter',
    currency: 'KES',
    fundingType: 'Paid',
    deadline: getFutureDateStr(6),
    startDate: '2026-05-04',
    endDate: '2026-08-07',
    duration: '3 Months',
    status: 'closing_soon',
    source: 'Safaricom Talent Acquisition Portal',
    sourceUrl: 'https://www.safaricom.co.ke/careers',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-02-01T10:00:00Z',
    featured: true,
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-02-15T08:00:00Z',
    attachmentDetails: {
      department: 'Technology, Digital & Network Operations',
      insuranceRequired: true,
      recommendationLetterRequired: true,
      applicationMethod: 'online_portal',
      contactEmail: 'talent@safaricom.co.ke',
    },
  },
  {
    id: 'opp-kengen-eng-2026',
    title: 'KenGen Industrial Attachment — Power Plants & Energy Systems',
    description:
      'Kenya Electricity Generating Company (KenGen) offers hands-on industrial training across Olkaria Geothermal, Seven Forks Hydro, and Kipevu Thermal stations for mechanical, electrical, and mechatronics engineering students.',
    provider: 'KenGen Kenya',
    organization: 'Kenya Electricity Generating Company PLC',
    type: 'Attachment',
    country: 'Kenya',
    countries: ['Kenya'],
    location: 'Naivasha (Olkaria) / Seven Forks / Nairobi, Kenya',
    remote: 'on_site',
    website: 'https://www.kengen.co.ke',
    applicationUrl: 'https://www.kengen.co.ke/careers/industrial-attachment',
    field: 'Engineering',
    fields: ['Electrical Engineering', 'Mechanical Engineering', 'Mechatronic Engineering', 'Renewable Energy', 'Civil Engineering'],
    eligibleUniversities: ['All Kenyan Universities and National Polytechnics'],
    eligibleProgrammes: [
      'BSc. Electrical & Electronic Engineering',
      'BSc. Mechanical Engineering',
      'BSc. Mechatronic Engineering',
      'BSc. Civil Engineering',
      'Diploma in Electrical/Mechanical Engineering',
    ],
    eligibleAcademicLevels: ['Year 3', 'Year 4', 'Diploma'],
    requiredSkills: ['Power Systems Basics', 'CAD Drafting / SolidWorks or AutoCAD', 'Electrical Safety Protocols'],
    preferredSkills: ['MATLAB / Simulink', 'Industrial Automation', 'PLC Programming'],
    minimumGPA: 2.8,
    fundingAmount: 'KSh 25,000 / month Stipend + Free Staff Transport to Station',
    currency: 'KES',
    fundingType: 'Paid',
    deadline: getFutureDateStr(14),
    startDate: '2026-05-15',
    endDate: '2026-08-15',
    duration: '3 Months',
    status: 'open',
    source: 'KenGen Human Resource & Training Directorate',
    sourceUrl: 'https://www.kengen.co.ke',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-02-10T14:30:00Z',
    featured: true,
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-02-10T14:30:00Z',
    attachmentDetails: {
      department: 'Geothermal & Hydro Power Generation Division',
      insuranceRequired: true,
      recommendationLetterRequired: true,
      applicationMethod: 'online_portal',
    },
  },
  {
    id: 'opp-chev-uk-2026',
    title: 'Chevening UK Government Masters Scholarship',
    description:
      'The UK government international awards programme aimed at developing global leaders. Enables outstanding emerging leaders from Kenya and around the world to pursue one-year master degrees in any subject at any UK university.',
    provider: 'UK Foreign, Commonwealth and Development Office (FCDO)',
    organization: 'British High Commission & Association of Commonwealth Universities',
    type: 'Scholarship',
    country: 'United Kingdom',
    countries: ['Kenya', 'Uganda', 'Tanzania', 'Nigeria', 'Ghana', 'India', 'Global (160+ Countries)'],
    location: 'United Kingdom (Any Accredited University)',
    remote: false,
    website: 'https://www.chevening.org',
    applicationUrl: 'https://www.chevening.org/scholarships/application-timeline/',
    field: 'All Fields',
    fields: ['Engineering', 'Data Science & AI', 'Public Policy', 'Law', 'Economics & Finance', 'Public Health', 'Renewable Energy'],
    eligibleUniversities: ['Open to graduates from all recognized universities'],
    eligibleProgrammes: ['1-Year Taught Master Degree Programmes in the UK'],
    eligibleAcademicLevels: ['Recent Graduate', 'Postgraduate', 'Masters'],
    requiredSkills: ['Demonstrated Leadership', 'Strategic Vision', 'Professional Impact'],
    preferredSkills: ['Minimum 2 years (2,800 hours) work experience/internships'],
    minimumGPA: 3.3, // Equivalent to Second Class Upper
    fundingAmount: 'Full University Tuition, Monthly Living Allowance, Return Flights & Visa Fees',
    currency: 'GBP',
    fundingType: 'Fully Funded',
    deadline: getFutureDateStr(60),
    startDate: '2026-09-15',
    endDate: '2027-09-30',
    duration: '1 Year',
    status: 'open',
    source: 'Official Chevening Secretariat (FCDO)',
    sourceUrl: 'https://www.chevening.org',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-01-20T11:00:00Z',
    featured: true,
    createdAt: '2026-01-10T12:00:00Z',
    updatedAt: '2026-02-18T10:00:00Z',
    scholarshipDetails: {
      coverageType: 'Full Funding',
      tuitionCoverage: true,
      accommodationCoverage: true,
      travelCoverage: true,
      livingAllowance: true,
      monthlyStipendAmount: '£1,400 / month (London) / £1,150 / month (Outside London)',
    },
  },
  {
    id: 'opp-goog-swe-intern-2026',
    title: 'Google Software Engineering Student Internship (Africa & Remote)',
    description:
      '12 to 14-week internship program where students collaborate on real-world engineering projects spanning Google Search, Android OS, Cloud Infrastructure, and Workspace products. Open to current university students returning to school after internship.',
    provider: 'Google LLC',
    organization: 'Google Africa & Engineering Hubs',
    type: 'Internship',
    country: 'Pan-Africa',
    countries: ['Kenya', 'Nigeria', 'South Africa', 'Ghana', 'Egypt', 'Remote'],
    location: 'Nairobi, Kenya / Johannesburg / Remote',
    remote: true,
    website: 'https://careers.google.com/students',
    applicationUrl: 'https://www.google.com/about/careers/applications/students/',
    field: 'Computer Science & Software',
    fields: ['Computer Science', 'Software Engineering', 'Electrical Engineering', 'Applied Mathematics', 'Information Technology'],
    eligibleUniversities: ['All accredited universities worldwide'],
    eligibleProgrammes: ['BSc. Computer Science', 'BSc. Software Engineering', 'BSc. Computer Engineering', 'Related STEM'],
    eligibleAcademicLevels: ['Year 2', 'Year 3', 'Year 4', 'Masters'],
    requiredSkills: ['Data Structures & Algorithms', 'C++, Java, Python, or Go', 'Problem Solving'],
    preferredSkills: ['System Design Basics', 'Open Source Contributions', 'Git & CI/CD'],
    minimumGPA: 3.2,
    fundingAmount: '$2,800 - $3,500 / month stipend + Relocation or Remote Setup Allowance',
    currency: 'USD',
    fundingType: 'Paid',
    deadline: getFutureDateStr(18),
    startDate: '2026-06-01',
    endDate: '2026-08-28',
    duration: '3 Months',
    status: 'open',
    source: 'Google Careers Students Portal',
    sourceUrl: 'https://careers.google.com',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-01-25T15:00:00Z',
    featured: true,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-02-12T16:00:00Z',
    attachmentDetails: {
      department: 'Google Core Engineering & Cloud Africa',
      applicationMethod: 'online_portal',
    },
  },
  {
    id: 'opp-kcb-grad-2026',
    title: 'KCB Bank Management & Fintech Graduate Trainee Programme',
    description:
      'An intensive 24-month fast-track leadership development program designed for ambitious graduates with passion for digital banking, quantitative finance, credit risk engineering, and software solutions across East Africa.',
    provider: 'KCB Group',
    organization: 'KCB Bank Kenya & East Africa Subsidiaries',
    type: 'Graduate Programme',
    country: 'Kenya',
    countries: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda', 'South Sudan', 'DRC'],
    location: 'Nairobi, Kenya (KCB Leadership Centre, Karen)',
    remote: 'hybrid',
    website: 'https://kcbgroup.com/careers',
    applicationUrl: 'https://kcbgroup.com/careers/graduate-recruitment',
    field: 'Business, Finance & Tech',
    fields: ['Economics', 'Finance', 'Computer Science', 'Actuarial Science', 'Statistics', 'Business Administration', 'Data Analytics'],
    eligibleUniversities: ['Recognized universities globally'],
    eligibleProgrammes: ['Bachelor Degree with Second Class Upper or First Class Honours'],
    eligibleAcademicLevels: ['Year 4', 'Recent Graduate'],
    requiredSkills: ['Financial Modeling / Quantitative Analysis', 'Data Literacy (Excel/SQL)', 'Communication & Presentation'],
    preferredSkills: ['Python for Data Analysis', 'Fintech Architecture Understanding', 'Leadership experience'],
    minimumGPA: 3.4,
    fundingAmount: 'KSh 110,000 / month Salary + Full Medical, Pension & Bonus',
    currency: 'KES',
    fundingType: 'Paid',
    deadline: getFutureDateStr(28),
    startDate: '2026-08-01',
    duration: '2 Years (Direct to Permanent Role)',
    status: 'open',
    source: 'KCB Group Official Careers Bulletin',
    sourceUrl: 'https://kcbgroup.com/careers',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-02-05T09:00:00Z',
    featured: false,
    createdAt: '2026-01-28T09:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z',
    jobDetails: {
      employmentType: 'graduate_trainee',
      salaryRange: 'KSh 100,000 - KSh 120,000 / month',
      experienceLevel: 'Graduate',
    },
  },
  {
    id: 'opp-equity-elp-2026',
    title: 'Equity Leaders Program (ELP) University Leadership Grant',
    description:
      'Flagship leadership and academic development initiative by Equity Group Foundation. Provides financial support, pre-university paid internships, global university application mentorship, and executive leadership workshops.',
    provider: 'Equity Group Foundation',
    organization: 'Equity Group Foundation & Equity Bank',
    type: 'Scholarship',
    country: 'Kenya',
    countries: ['Kenya', 'Rwanda', 'Uganda', 'DRC'],
    location: 'Nairobi, Kenya & Regional Branches',
    remote: false,
    website: 'https://equitygroupfoundation.com',
    applicationUrl: 'https://equitygroupfoundation.com/education-leadership/',
    field: 'All Fields',
    fields: ['Medicine', 'Engineering', 'Law', 'Computer Science', 'Commerce', 'Actuarial Science'],
    eligibleUniversities: ['Accredited Kenyan Public & Private Universities + Global Partners (Harvard, MIT, Stanford, Oxford)'],
    eligibleProgrammes: ['All Undergraduate Degree Programmes'],
    eligibleAcademicLevels: ['Undergraduate', 'Year 1', 'Year 2', 'Year 3', 'Year 4'],
    requiredSkills: ['Academic Distinction', 'Community Impact', 'Integrity'],
    preferredSkills: ['Peer Mentoring', 'Public Speaking'],
    minimumGPA: 3.5,
    fundingAmount: 'KSh 160,000 / Academic Year + Paid Internship (KSh 40,000/mo) + Mentorship',
    currency: 'KES',
    fundingType: 'Fully Funded',
    deadline: getFutureDateStr(3),
    startDate: '2026-06-01',
    duration: 'Entire Degree Duration',
    status: 'closing_soon',
    source: 'Equity Group Foundation Official Portal',
    sourceUrl: 'https://equitygroupfoundation.com',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-01-10T08:00:00Z',
    featured: true,
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z',
    scholarshipDetails: {
      coverageType: 'Tuition & Stipend',
      tuitionCoverage: true,
      accommodationCoverage: true,
      travelCoverage: false,
      livingAllowance: true,
      monthlyStipendAmount: 'KSh 40,000 during work rotations',
    },
  },
  {
    id: 'opp-daad-epos-2026',
    title: 'DAAD EPOS Postgraduate Scholarship in Germany',
    description:
      'German Academic Exchange Service (DAAD) development-related postgraduate courses scholarship. Covers full tuition, monthly stipend, health insurance, and German language training for students pursuing Master or PhD degrees in Germany.',
    provider: 'DAAD Germany',
    organization: 'German Federal Ministry for Economic Cooperation and Development (BMZ)',
    type: 'Scholarship',
    country: 'Germany',
    countries: ['Kenya', 'Uganda', 'Tanzania', 'Nigeria', 'Ghana', 'Ethiopia', 'Developing Countries'],
    location: 'Germany (Technical University of Munich, Heidelberg, RWTH Aachen, Berlin)',
    remote: false,
    website: 'https://www.daad.de',
    applicationUrl: 'https://www.daad.de/en/information-services-for-higher-education-institutions/programmes-for-heis/epos/',
    field: 'STEM, Economics & Development',
    fields: ['Renewable Energy', 'Civil & Environmental Engineering', 'Public Health', 'Agricultural Economics', 'Computer Science'],
    eligibleUniversities: ['Graduates of recognized universities in partner countries'],
    eligibleProgrammes: ['Approved EPOS Master and Doctoral programmes in Germany'],
    eligibleAcademicLevels: ['Recent Graduate', 'Postgraduate', 'Masters', 'PhD'],
    requiredSkills: ['Strong Academic Record', 'Subject Motivation', 'English or German Proficiency (IELTS/TOEFL)'],
    preferredSkills: ['At least 2 years professional experience post-bachelor'],
    minimumGPA: 3.4,
    fundingAmount: '€934 / month Stipend + Full Tuition + Health Insurance + Travel Subsidy',
    currency: 'EUR',
    fundingType: 'Fully Funded',
    deadline: getFutureDateStr(50),
    startDate: '2026-10-01',
    endDate: '2028-09-30',
    duration: '2 Years',
    status: 'open',
    source: 'DAAD Regional Office Nairobi & Bonn',
    sourceUrl: 'https://www.daad.de',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-01-18T14:00:00Z',
    featured: true,
    createdAt: '2026-01-10T12:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z',
    scholarshipDetails: {
      coverageType: 'Full Funding',
      tuitionCoverage: true,
      accommodationCoverage: true,
      travelCoverage: true,
      livingAllowance: true,
      monthlyStipendAmount: '€934/mo (Masters) / €1,300/mo (PhD)',
    },
  },
  {
    id: 'opp-andela-fellow-2026',
    title: 'Andela Technical Fellowship & Remote Engineering Accelerator',
    description:
      'A 6-month intensive remote fellowship designed to bridge the gap between academic computer science and global engineering teams. Fellows build cloud-native applications with guidance from senior staff engineers.',
    provider: 'Andela Inc.',
    organization: 'Andela Learning Community',
    type: 'Fellowship',
    country: 'Global',
    countries: ['Kenya', 'Nigeria', 'Rwanda', 'Ghana', 'Egypt', 'South Africa', 'Remote Global'],
    location: 'Fully Remote (Worldwide)',
    remote: true,
    website: 'https://andela.com',
    applicationUrl: 'https://andela.com/fellowship-apply/',
    field: 'Software Engineering',
    fields: ['Full-Stack Development', 'React & TypeScript', 'Backend Microservices (Node/Go/Python)', 'Cloud Architecture'],
    eligibleUniversities: ['Open to all students and self-taught developers'],
    eligibleProgrammes: ['Computer Science', 'Software Engineering', 'Information Technology', 'Self-Taught Developers'],
    eligibleAcademicLevels: ['Year 2', 'Year 3', 'Year 4', 'Recent Graduate'],
    requiredSkills: ['JavaScript / TypeScript', 'React or Vue', 'Git & GitHub', 'REST APIs'],
    preferredSkills: ['Docker', 'PostgreSQL', 'Unit Testing (Jest/Vitest)', 'GraphQL'],
    fundingAmount: '$1,200 / month Fellow Honorarium + High-Speed Internet Subsidy',
    currency: 'USD',
    fundingType: 'Paid',
    deadline: getFutureDateStr(21),
    startDate: '2026-05-01',
    duration: '6 Months',
    status: 'open',
    source: 'Andela Talent Network',
    sourceUrl: 'https://andela.com',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-02-08T16:00:00Z',
    featured: false,
    createdAt: '2026-01-25T11:00:00Z',
    updatedAt: '2026-02-14T09:00:00Z',
    jobDetails: {
      employmentType: 'contract',
      salaryRange: '$1,000 - $1,500 / month',
      experienceLevel: 'Student',
    },
  },
  {
    id: 'opp-kplc-elec-2026',
    title: 'Kenya Power (KPLC) Electrical Engineering Attachment',
    description:
      'Kenya Power & Lighting Company (KPLC) invites 3rd and 4th-year electrical and energy engineering students for hands-on substation maintenance, grid distribution, smart metering, and high-voltage transmission operations.',
    provider: 'Kenya Power (KPLC)',
    organization: 'The Kenya Power and Lighting Company PLC',
    type: 'Attachment',
    country: 'Kenya',
    countries: ['Kenya'],
    location: 'Nairobi (Stima Plaza / Ruaraka) & All 8 Regional Hubs',
    remote: 'on_site',
    website: 'https://www.kplc.co.ke',
    applicationUrl: 'https://www.kplc.co.ke/category/careers/attachment',
    field: 'Engineering',
    fields: ['Electrical & Electronics Engineering', 'Telecommunications', 'Mechatronics', 'Civil Engineering'],
    eligibleUniversities: ['All Kenyan Universities and National Polytechnics accredited by EBK / TVET'],
    eligibleProgrammes: [
      'BSc. Electrical & Electronic Engineering',
      'BSc. Telecommunications Engineering',
      'Diploma in Electrical Engineering (Power Option)',
    ],
    eligibleAcademicLevels: ['Year 3', 'Year 4', 'Diploma'],
    requiredSkills: ['Single-Line Diagram Interpretation', 'Basic Power Distribution', 'Electrical Safety & PPE compliance'],
    preferredSkills: ['Autodesk AutoCAD Electrical', 'Relay Testing Knowledge', 'Troubleshooting'],
    minimumGPA: 2.7,
    fundingAmount: 'KSh 20,000 / month Transport Subsidy + Official NITA Training Assessment',
    currency: 'KES',
    fundingType: 'Paid',
    deadline: getFutureDateStr(8),
    startDate: '2026-05-18',
    endDate: '2026-08-21',
    duration: '3 Months',
    status: 'open',
    source: 'Kenya Power Institute of Energy Studies & Research (IESR)',
    sourceUrl: 'https://www.kplc.co.ke',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-02-02T13:00:00Z',
    featured: false,
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-02-12T14:00:00Z',
    attachmentDetails: {
      department: 'Network Operations & Substation Maintenance',
      insuranceRequired: true,
      recommendationLetterRequired: true,
      applicationMethod: 'online_portal',
      contactEmail: 'attachments@kplc.co.ke',
    },
  },
  {
    id: 'opp-mit-solv-comp-2026',
    title: 'MIT Solve Global Climate & Health Innovation Challenge',
    description:
      'Annual global competition for student innovators and tech founders building scalable solutions for climate adaptation, maternal health, and youth economic prosperity. Finalists pitch at MIT and receive non-dilutive seed funding.',
    provider: 'Massachusetts Institute of Technology (MIT)',
    organization: 'MIT Solve & Global Philanthropy Partners',
    type: 'Competition',
    country: 'Global',
    countries: ['Global', 'Kenya', 'United States', 'India', 'Brazil', 'Nigeria', 'UK'],
    location: 'Cambridge, MA, USA & Virtual',
    remote: true,
    website: 'https://solve.mit.edu',
    applicationUrl: 'https://solve.mit.edu/challenges',
    field: 'Innovation, Tech & Health',
    fields: ['Computer Science', 'Biomedical Engineering', 'Renewable Energy', 'Agriculture', 'Public Health', 'Business Innovation'],
    eligibleUniversities: ['Students and researchers worldwide'],
    eligibleProgrammes: ['Undergraduate, Postgraduate, and PhD Student Teams'],
    eligibleAcademicLevels: ['All Levels', 'Undergraduate', 'Postgraduate'],
    requiredSkills: ['Prototyping / MVP Development', 'Impact Measurement', 'Pitch Presentation'],
    preferredSkills: ['IoT / Sensor Integration', 'Mobile App Development', 'Business Model Canvas'],
    fundingAmount: '$10,000 - $100,000 Non-dilutive Grant Funding + MIT Mentorship',
    currency: 'USD',
    fundingType: 'Grant',
    deadline: getFutureDateStr(35),
    startDate: '2026-09-20',
    duration: '9-Month Accelerator Cycle',
    status: 'open',
    source: 'MIT Solve Official Challenge Page',
    sourceUrl: 'https://solve.mit.edu',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-01-30T10:00:00Z',
    featured: true,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-02-15T11:00:00Z',
  },
  {
    id: 'opp-ms-adc-junior-2026',
    title: 'Microsoft Africa Development Centre (ADC) Junior Cloud Software Engineer',
    description:
      'Full-time entry-level engineering position at the Microsoft ADC Nairobi engineering center. Work on Azure Core Services, Identity Security, Office 365, and AI Copilot capabilities alongside global software engineering teams.',
    provider: 'Microsoft Corporation',
    organization: 'Microsoft Africa Development Centre (ADC Nairobi)',
    type: 'Job',
    country: 'Kenya',
    countries: ['Kenya', 'Nigeria', 'Pan-Africa'],
    location: 'Nairobi, Kenya (Dunhill Towers, Westlands)',
    remote: 'hybrid',
    website: 'https://careers.microsoft.com',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/1749210/Software-Engineer-Nairobi',
    field: 'Software Engineering & Cloud',
    fields: ['Computer Science', 'Software Engineering', 'Electrical Engineering', 'Information Technology'],
    eligibleUniversities: ['Accredited universities globally'],
    eligibleProgrammes: ['BSc. Computer Science', 'BSc. Computer Engineering', 'BSc. Electrical Engineering', 'Related STEM Degree'],
    eligibleAcademicLevels: ['Year 4', 'Recent Graduate'],
    requiredSkills: ['C#, Java, C++, or TypeScript', 'Object-Oriented Design', 'Data Structures & Algorithms', 'Unit Testing'],
    preferredSkills: ['Azure / Cloud Services', 'Distributed Systems', 'CI/CD Pipelines'],
    minimumGPA: 3.3,
    fundingAmount: 'KSh 280,000 - KSh 380,000 / month + Stock Grants (RSUs) + Comprehensive Healthcare',
    currency: 'KES',
    fundingType: 'Paid',
    deadline: getFutureDateStr(25),
    startDate: '2026-07-01',
    duration: 'Full-Time Permanent',
    status: 'open',
    source: 'Microsoft Global Careers Portal',
    sourceUrl: 'https://careers.microsoft.com',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-02-01T09:00:00Z',
    featured: true,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-14T11:00:00Z',
    jobDetails: {
      employmentType: 'full_time',
      salaryRange: 'KSh 280,000 - KSh 380,000 / month',
      experienceLevel: 'Entry Level',
      probationPeriod: '6 Months',
    },
  },
  {
    id: 'opp-red-cross-vol-2026',
    title: 'Kenya Red Cross Youth Humanitarian & Health Volunteer Programme',
    description:
      'Engage in community first response, disaster triage, youth mental health outreach, and emergency medical logistics across campus chapters and regional Red Cross branches in Kenya.',
    provider: 'Kenya Red Cross Society',
    organization: 'Kenya Red Cross Youth Directorate',
    type: 'Volunteering',
    country: 'Kenya',
    countries: ['Kenya'],
    location: 'Nationwide Campuses & County Branches',
    remote: false,
    website: 'https://www.redcross.or.ke',
    applicationUrl: 'https://www.redcross.or.ke/volunteer-with-us/',
    field: 'Health & Community Development',
    fields: ['Medicine & Surgery', 'Nursing', 'Public Health', 'Psychology & Counseling', 'Social Work', 'General Studies'],
    eligibleUniversities: ['All university and college campuses with registered Red Cross Chapters'],
    eligibleProgrammes: ['All students in good academic standing'],
    eligibleAcademicLevels: ['All Levels', 'Year 1', 'Year 2', 'Year 3', 'Year 4'],
    requiredSkills: ['Empathy', 'Teamwork', 'First Aid Certified (or willingness to train)'],
    preferredSkills: ['Disaster Preparedness', 'Peer Education', 'Community Organizing'],
    fundingAmount: 'Certificate of Service + Field Transport & Meals Allowance',
    currency: 'KES',
    fundingType: 'Unpaid',
    deadline: getFutureDateStr(90),
    startDate: '2026-04-01',
    duration: 'Ongoing / Semester-based',
    status: 'open',
    source: 'Kenya Red Cross Youth Affairs Portal',
    sourceUrl: 'https://www.redcross.or.ke',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-01-10T10:00:00Z',
    featured: false,
    createdAt: '2026-01-05T12:00:00Z',
    updatedAt: '2026-02-01T12:00:00Z',
  },
  {
    id: 'opp-google-genai-train-2026',
    title: 'Google Cloud & Gemini GenAI Student Developer Certification Program',
    description:
      'Free technical training track and certification vouchers for university students to build generative AI solutions using Gemini API, Vertex AI, and Google Cloud Run. Includes hands-on Qwiklabs credits and certification exam voucher.',
    provider: 'Google for Developers',
    organization: 'Google Developer Student Clubs (GDSC) & Google Cloud',
    type: 'Training',
    country: 'Global',
    countries: ['Global', 'Kenya', 'Pan-Africa', 'Europe', 'Americas', 'Asia'],
    location: '100% Online / Virtual Hands-on Labs',
    remote: true,
    website: 'https://developers.google.com/students',
    applicationUrl: 'https://developers.google.com/community/gdsc',
    field: 'Artificial Intelligence & Cloud',
    fields: ['Computer Science', 'Data Science', 'Software Engineering', 'Applied Mathematics', 'Information Technology'],
    eligibleUniversities: ['All students currently enrolled in an accredited higher education institution'],
    eligibleProgrammes: ['Any undergraduate or graduate student with programming basics'],
    eligibleAcademicLevels: ['All Levels', 'Year 1', 'Year 2', 'Year 3', 'Year 4', 'Masters'],
    requiredSkills: ['Basic Python or JavaScript', 'REST APIs', 'Curiosity for AI'],
    preferredSkills: ['Prompt Engineering', 'LangChain / Vertex AI concepts'],
    fundingAmount: '100% Free Course ($500 Value) + Free Google Cloud Certification Exam Voucher',
    currency: 'USD',
    fundingType: 'Fully Funded',
    deadline: getFutureDateStr(40),
    startDate: '2026-04-15',
    duration: '8 Weeks Self-Paced',
    status: 'open',
    source: 'Google for Developers Official Announcement',
    sourceUrl: 'https://developers.google.com',
    verified: true,
    verifiedBy: 'Enemind Verification Office',
    verifiedAt: '2026-02-01T12:00:00Z',
    featured: true,
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-02-10T15:00:00Z',
  },
];
